Clinic/Models/Record.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Clinic.Models
{
    public class Record
    {
        public int ID { get; set; }
        public string Document { get; set; }
        public string Description { get; set; }

        [ForeignKey("Patient")]
        public int PatientID { get; set; }
        public virtual Patient Patient { get; set; }
    }
}

Clinic/Controllers/RecordsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Clinic.Models;
using Clinic.Models.ViewModels;
using Clinic.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace Clinic.Controllers
{
    public class RecordsController : Controller
    {
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly RecordsServices recordeService;
        private readonly IService<Patient> patientservice;

        public RecordsController( IHostingEnvironment hostingEnvironment, RecordsServices RecordeService
            , IService<Patient> Patientservice)
        {
            this.hostingEnvironment = hostingEnvironment;
            recordeService = RecordeService;
            patientservice = Patientservice;
        }
        public IActionResult Index()
        {
            return View(recordeService.GetAll());
        }

        [HttpGet]
        public IActionResult Create(int? id)
        {
            ViewBag.ID = id;
            ViewBag.PatientName = patientservice.GetOne(id).Name;
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateRecordViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;

                if (model.Document != null)
                {
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");

                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Document.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    model.Document.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                Record record = new Record
                {
                    PatientID = model.PatientID,
                    Description = model.Description,
                    Document = uniqueFileName
                };

                recordeService.insert(record);
                return RedirectToAction("Edit", "Patients", new { id = record.PatientID });
            }

            return View();
        }
        [HttpGet]
        public IActionResult AddRecord()
        {
            ViewBag.Patients = patientservice.GetAll();
            return View();
        }
        [HttpPost]
        public IActionResult AddRecord(CreateRecordViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;

                if (model.Document != null)
                {
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");

                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Document.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    model.Document.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                Record record = new Record
                {
                    PatientID = model.PatientID,
                    Description = model.Description,
                    Document = uniqueFileName
                };

                recordeService.insert(record);
                return RedirectToAction("Edit", "Patients", new { id = record.PatientID });
            }

            return View();
        }

        public void DownloadDocument()
        {
            using (WebClient client = new WebClient())
            {
                client.DownloadFile(new Uri("https://localhost:44352/images/59c6c6e4-1c12-408a-9b9b-d518127780a8_m1.jpg??%27noimage.png%27&v=-OjQeJYyHj-R8B83iILDnZ-FGtnmUQ42SmBzTY9CtCY"), @"c:\temp\image35.png");   
            }
        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var record = recordeService.GetOne(id);
            if (record == null)
            {
                return NotFound();
            }
            CreateRecordViewModel model = new CreateRecordViewModel
            {
                Description = record.Description,
                PatientID = record.PatientID
            };
            ViewBag.Document = record.Document;
            return View(model);
        }

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CreateRecordViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;

                if (model.Document != null)
                {
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");

                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Document.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    model.Document.CopyTo(new FileStream(filePath, FileMode.Create));
                }
                Record record = new Record()
                {
                    Description = model.Description,
                    PatientID = model.PatientID,
                    Document = uniqueFileName
                };
                try
                {
                    recordeService.Update(record,id);
                    
                }
                catch 
                {
                    
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
    }
}

Clinic/Views/Records/AddRecord.cshtml
@model Clinic.Models.ViewModels.CreateRecordViewModel


@{
    ViewData["Title"] = "Create";
    List<Patient> patients = ViewBag.Patients;
    var Patients = new SelectList(patients, "ID", "Name");
}

<br />
<br />
<h4>Create Record for Patient </h4>
<br />
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="AddRecord">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<input type="hidden" asp-for="PatientID" />*@
            <div class="form-group">
                <label  class="control-label">Patient</label>
                @Html.DropDownList("PatientID", Patients, new { @class = "form-control" })
                @*<input type="text" asp-for="Description" class="form-control" />*@
                <span asp-validation-for="PatientID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input type="text" asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Document" class=" control-label"></label>
                <div>
                    <div class="custom-file">
                        <input asp-for="Document" class="form-control custom-file-input" />
                        <label class="custom-file-label">Choose Image..</label>
                    </div>
                </div>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            @section Scripts {
                @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
                <script>
                    $(document).ready(function () {
                        $('.custom-file-input').on("change", function () {
                            var fileName = $(this).val().split("\\").pop();
                            $(this).next('.custom-file-label').html(fileName);
                        });
                    });
                </script>
            }
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Clinic/Views/Records/Create.cshtml
@model Clinic.Models.ViewModels.CreateRecordViewModel

@{
    ViewData["Title"] = "Create";
    var PatientID = ViewBag.ID;
    var PatientName = ViewBag.PatientName;
}

<br />
<br />
<h4>Create Record for Patient @PatientName</h4>
<br />
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PatientID" value="@PatientID" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input type="text" asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Document" class=" control-label"></label>
                <div>
                    <div class="custom-file">
                        <input asp-for="Document" class="form-control custom-file-input" />
                        <label class="custom-file-label">Choose Image..</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            @section Scripts {
                @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
                <script>
                    $(document).ready(function () {
                        $('.custom-file-input').on("change", function () {
                            var fileName = $(this).val().split("\\").pop();
                            $(this).next('.custom-file-label').html(fileName);
                        });
                    });
                </script>
            }
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Clinic/Views/Records/Edit.cshtml
@model Clinic.Models.ViewModels.CreateRecordViewModel

@{
    ViewData["Title"] = "Edit";
    var photoPath = "~/images/" + (ViewBag.Document ?? "noimage.png");

}

<h1>Edit</h1>

<div class="row">
    <div class="col-md-8 col-sm-8">
        <form enctype="multipart/form-data" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="input-group mb-2">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">Name</span>
                </div>
                <input type="text" class="form-control" asp-for="Description" aria-describedby="basic-addon1">
            </div>
            
            <div class="input-group mb-2">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">
                        <img style="height:23px;width:auto" src="@photoPath" asp-append-version="true" />
                    </span>
                </div>
                <div class="custom-file">
                    <input asp-for="Document" class="form-control custom-file-input " />
                    <label class="custom-file-label">Choose Image..</label>
                </div>
                <span asp-validation-for="Document" class="text-danger"></span>
            </div>
            @*<div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Mobile</span>
                    </div>
                    <input asp-for="Mobile" class="form-control" />
                    <span asp-validation-for="Mobile" class="text-danger"></span>
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">TobaccoUsage</span>
                    </div>
                    <input asp-for="TobaccoUsage" class="form-control" />
                    <span asp-validation-for="TobaccoUsage" class="text-danger"></span>
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Alchol</span>
                    </div>
                    <input asp-for="Alchol" class="form-control" />
                    <span asp-validation-for="Alchol" class="text-danger"></span>
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">History</span>
                    </div>
                    <input asp-for="History" class="form-control" />
                    <span asp-validation-for="History" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-danger"><i class="fas fa-reply"></i> Back to List</a>
            </div>
            <hr />
            
           
            @section Scripts {
                @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
                <script>
                    $(document).ready(function () {
                        $('.custom-file-input').on("change", function () {
                            var fileName = $(this).val().split("\\").pop();
                            $(this).next('.custom-file-label').html(fileName);
                        });
                    }

                </script>
            }
        </form>
    </div>
</div>

Clinic/Views/Records/Index.cshtml
@model List<Clinic.Models.Record>
@{
    ViewData["Title"] = "Index";
}

<h1>All Mediacal Records</h1>
<a class="btn btn-success" asp-action="AddRecord" asp-controller="Records">Add+</a>
@if (Model.Count == 0)
{
    <h1>No Records</h1>
}
else
{
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Patient</th>
                <th scope="col">Document</th>
                <th scope="col">Description</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @item.Patient.Name
                </td>
                <td>
                    <img style="height:80px;width:auto" src="~/images/@item.Document??'noimage.png'" asp-append-version="true" />
                </td>
                <td><p>@item.Description</p></td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
}